SELECT
	C.CATEGORY_NAME AS CATEGORIA,
	COUNT(*) AS NUM_LINEAS,
	COUNT(DISTINCT P.PRODUCT_ID) AS NUM_PRODUCTOS,
	ROUND(SUM(P.UNIT_PRICE::NUMERIC * O.QUANTITY * (1 - O.DISCOUNT::NUMERIC)), 2) AS FACTURACION
FROM
	PRODUCTS P
	INNER JOIN CATEGORIES C USING (CATEGORY_ID)
	INNER JOIN ORDER_DETAILS O USING (PRODUCT_ID)
GROUP BY
	C.CATEGORY_NAME
HAVING
	SUM(P.UNIT_PRICE::NUMERIC * O.QUANTITY * (1 - O.DISCOUNT::NUMERIC)) > 100000
ORDER BY
	SUM(P.UNIT_PRICE::NUMERIC * O.QUANTITY * (1 - O.DISCOUNT::NUMERIC)) DESC;