SELECT
	COALESCE(C.COUNTRY, P.COUNTRY) AS PAIS,
	COALESCE(C.NUM_CLIENTES, 0) AS NUM_CLIENTES,
	COALESCE(P.NUM_PROVEEDORES, 0) AS NUM_PROVEEDORES,
	CASE
		WHEN C.NUM_CLIENTES > 0
		AND P.NUM_PROVEEDORES > 0 THEN 'AMBOS'
		WHEN C.NUM_CLIENTES > 0 THEN 'SOLO CLIENTES'
		ELSE 'SOLO PROVEEDORES'
	END AS TIPO_PRESENCIA
FROM
	(
		SELECT
			COUNTRY,
			COUNT(*) AS NUM_CLIENTES
		FROM
			CUSTOMERS
		GROUP BY
			COUNTRY
	) C
	FULL JOIN (
		SELECT
			COUNTRY,
			COUNT(*) AS NUM_PROVEEDORES
		FROM
			SUPPLIERS
		GROUP BY
			COUNTRY
	) P ON C.COUNTRY = P.COUNTRY
ORDER BY
	PAIS;