WITH
	VENTAS_MENSUALES AS (
		SELECT
			DATE_TRUNC('month', O.ORDER_DATE) AS MES,
			SUM(OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT)) AS FACTURACION
		FROM
			ORDERS O
			JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
		WHERE
			EXTRACT(
				YEAR
				FROM
					O.ORDER_DATE
			) = 1997
		GROUP BY
			DATE_TRUNC('month', O.ORDER_DATE)
	)
SELECT
	TO_CHAR(MES, 'YYYY-MM') AS MES,
	ROUND(FACTURACION::NUMERIC, 2) AS FACTURACION,
	ROUND(
		SUM(FACTURACION) OVER (
			ORDER BY
				MES ROWS BETWEEN UNBOUNDED PRECEDING
				AND CURRENT ROW
		)::NUMERIC,
		2
	) AS ACUMULADO,
	ROUND(
		AVG(FACTURACION) OVER (
			ORDER BY
				MES ROWS BETWEEN 2 PRECEDING
				AND CURRENT ROW
		)::NUMERIC,
		2
	) AS MEDIA_MOVIL_3M,
	ROUND(
		LAG(FACTURACION) OVER (
			ORDER BY
				MES
		)::NUMERIC,
		2
	) AS MES_ANTERIOR,
	ROUND(
		(
			100.0 * (
				FACTURACION - LAG(FACTURACION) OVER (
					ORDER BY
						MES
				)
			) / NULLIF(
				LAG(FACTURACION) OVER (
					ORDER BY
						MES
				),
				0
			)
		)::NUMERIC,
		2
	) AS VARIACION_PCT
FROM
	VENTAS_MENSUALES
ORDER BY
	MES;