WITH
	VENTAS_CATEGORIA AS (
		SELECT
			COALESCE(C.CATEGORY_NAME, 'TOTAL GENERAL') AS CATEGORIA,
			ROUND(
				SUM(
					CASE
						WHEN EXTRACT(
							YEAR
							FROM
								O.ORDER_DATE
						) = 1996 THEN OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT)
					END
				)::NUMERIC,
				2
			) AS F_1996,
			ROUND(
				SUM(
					CASE
						WHEN EXTRACT(
							YEAR
							FROM
								O.ORDER_DATE
						) = 1997 THEN OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT)
					END
				)::NUMERIC,
				2
			) AS F_1997,
			ROUND(
				SUM(
					CASE
						WHEN EXTRACT(
							YEAR
							FROM
								O.ORDER_DATE
						) = 1998 THEN OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT)
					END
				)::NUMERIC,
				2
			) AS F_1998,
			ROUND(
				SUM(OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT))::NUMERIC,
				2
			) AS TOTAL
		FROM
			CATEGORIES C
			JOIN PRODUCTS P USING (CATEGORY_ID)
			JOIN ORDER_DETAILS OD USING (PRODUCT_ID)
			JOIN ORDERS O USING (ORDER_ID)
		GROUP BY
			ROLLUP (C.CATEGORY_NAME)
	),
	TOTALES AS (
		SELECT
			TOTAL
		FROM
			VENTAS_CATEGORIA
		WHERE
			CATEGORIA = 'TOTAL GENERAL'
	)
SELECT
	V.CATEGORIA,
	COALESCE(V.F_1996, 0) AS F_1996,
	COALESCE(V.F_1997, 0) AS F_1997,
	COALESCE(V.F_1998, 0) AS F_1998,
	V.TOTAL,
	ROUND((100.0 * V.TOTAL / T.TOTAL)::NUMERIC, 2) AS PESO_PCT,
	CASE
		WHEN V.CATEGORIA = 'TOTAL GENERAL' THEN 'N/A'
		WHEN V.F_1998 > V.F_1997 THEN 'CRECE'
		ELSE 'DECRECE'
	END AS TENDENCIA
FROM
	VENTAS_CATEGORIA V,
	TOTALES T
ORDER BY
	(V.CATEGORIA = 'TOTAL GENERAL'),
	V.TOTAL DESC;