SELECT
	C.COMPANY_NAME AS CLIENTE,
	C.COUNTRY AS PAIS,
	COUNT(O.ORDER_ID) AS PEDIDOS_REALIZADOS
FROM
	CUSTOMERS C
	LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE
	NOT EXISTS (
		SELECT
			1
		FROM
			ORDERS O2
			JOIN ORDER_DETAILS OD ON O2.ORDER_ID = OD.ORDER_ID
			JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
			JOIN CATEGORIES CAT ON P.CATEGORY_ID = CAT.CATEGORY_ID
		WHERE
			O2.CUSTOMER_ID = C.CUSTOMER_ID
			AND CAT.CATEGORY_NAME = 'Seafood'
	)
GROUP BY
	C.CUSTOMER_ID,
	C.COMPANY_NAME,
	C.COUNTRY
ORDER BY
	PEDIDOS_REALIZADOS DESC,
	CLIENTE ASC;