SELECT
	E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLEADO,
	E.TITLE AS CARGO,
	COALESCE(
		J.FIRST_NAME || ' ' || J.LAST_NAME,
		'DIRECCIÓN GENERAL'
	) AS RESPONSABLE,
	COALESCE(J.TITLE, 'DIRECCIÓN GENERAL') AS CARGO_RESPONSABLE
FROM
	EMPLOYEES E
	LEFT JOIN EMPLOYEES J ON E.REPORTS_TO = J.EMPLOYEE_ID
ORDER BY
	RESPONSABLE,
	EMPLEADO;