SELECT
	C.COMPANY_NAME AS CLIENTE,
	C.COUNTRY AS PAIS,
	COUNT(O.ORDER_ID) AS NUM_PEDIDOS,
	COALESCE(
		TO_CHAR(MAX(O.ORDER_DATE), 'YYYY-MM-DD'),
		'SIN PEDIDOS'
	) AS ULTIMO_PEDIDO
FROM
	CUSTOMERS C
	LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY
	C.CUSTOMER_ID,
	C.COMPANY_NAME,
	C.COUNTRY
ORDER BY
	NUM_PEDIDOS ASC,
	CLIENTE ASC;