WITH
	VENTAS_PRODUCTO AS (
		SELECT
			C.CATEGORY_NAME AS CATEGORIA,
			P.PRODUCT_ID,
			P.PRODUCT_NAME AS PRODUCTO,
			SUM(OD.QUANTITY) AS UNIDADES,
			SUM(OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT)) AS FACTURACION
		FROM
			PRODUCTS P
			JOIN CATEGORIES C ON P.CATEGORY_ID = C.CATEGORY_ID
			JOIN ORDER_DETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
		GROUP BY
			C.CATEGORY_NAME,
			P.PRODUCT_ID,
			P.PRODUCT_NAME
	),
	RANKINGS AS (
		SELECT
			CATEGORIA,
			PRODUCTO,
			UNIDADES,
			ROUND(FACTURACION::NUMERIC, 2) AS FACTURACION,
			DENSE_RANK() OVER (
				PARTITION BY
					CATEGORIA
				ORDER BY
					FACTURACION DESC
			) AS POSICION_EN_CATEGORIA,
			DENSE_RANK() OVER (
				ORDER BY
					FACTURACION DESC
			) AS POSICION_GLOBAL
		FROM
			VENTAS_PRODUCTO
	)
SELECT
	CATEGORIA,
	POSICION_EN_CATEGORIA,
	PRODUCTO,
	UNIDADES,
	FACTURACION,
	POSICION_GLOBAL
FROM
	RANKINGS
WHERE
	POSICION_EN_CATEGORIA <= 3
ORDER BY
	CATEGORIA,
	POSICION_EN_CATEGORIA;