SELECT
	'CLIENTE' AS ORIGEN,
	UPPER(CONTACT_NAME) AS CONTACTO,
	COMPANY_NAME AS ORGANIZACION,
	CITY AS CIUDAD,
	COUNTRY AS PAIS
FROM
	CUSTOMERS
UNION ALL
SELECT
	'PROVEEDOR' AS ORIGEN,
	UPPER(CONTACT_NAME) AS CONTACTO,
	COMPANY_NAME AS ORGANIZACION,
	CITY AS CIUDAD,
	COUNTRY AS PAIS
FROM
	SUPPLIERS
UNION ALL
SELECT
	'EMPLEADO' AS ORIGEN,
	UPPER(FIRST_NAME || ' ' || LAST_NAME) AS CONTACTO,
	'NORTHWIND TRADERS' AS ORGANIZACION,
	CITY AS CIUDAD,
	COUNTRY AS PAIS
FROM
	EMPLOYEES
ORDER BY
	ORIGEN,
	PAIS;