SELECT
	C.CATEGORY_NAME AS CATEGORIA,
	A.ANIO,
	ROUND(COALESCE(V.FACTURACION, 0)::NUMERIC, 2) AS FACTURACION
FROM
	CATEGORIES C
	CROSS JOIN (
		SELECT DISTINCT
			EXTRACT(
				YEAR
				FROM
					ORDER_DATE
			) AS ANIO
		FROM
			ORDERS
	) A
	LEFT JOIN (
		SELECT
			P.CATEGORY_ID,
			EXTRACT(
				YEAR
				FROM
					O.ORDER_DATE
			) AS ANIO,
			SUM(OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT)) AS FACTURACION
		FROM
			ORDERS O
			JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
			JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
		GROUP BY
			P.CATEGORY_ID,
			EXTRACT(
				YEAR
				FROM
					O.ORDER_DATE
			)
	) V ON C.CATEGORY_ID = V.CATEGORY_ID
	AND A.ANIO = V.ANIO
ORDER BY
	CATEGORIA,
	ANIO;