SELECT
	SUB.COMPANY_NAME AS CLIENTE,
	SUB.COUNTRY AS PAIS,
	COUNT(SUB.ORDER_ID) AS NUM_PEDIDOS,
	ROUND(SUM(SUB.IMPORTE_PEDIDO)::NUMERIC, 2) AS IMPORTE_TOTAL,
	ROUND(AVG(SUB.IMPORTE_PEDIDO)::NUMERIC, 2) AS TICKET_MEDIO
FROM
	(
		SELECT
			C.CUSTOMER_ID,
			C.COMPANY_NAME,
			C.COUNTRY,
			O.ORDER_ID,
			SUM(OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT)) AS IMPORTE_PEDIDO
		FROM
			CUSTOMERS C
			JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
			JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
		GROUP BY
			C.CUSTOMER_ID,
			C.COMPANY_NAME,
			C.COUNTRY,
			O.ORDER_ID
	) AS SUB
GROUP BY
	SUB.CUSTOMER_ID,
	SUB.COMPANY_NAME,
	SUB.COUNTRY
ORDER BY
	TICKET_MEDIO DESC
LIMIT
	15;