WITH
	MEDIA_CATALOGO AS (
		SELECT
			AVG(UNIT_PRICE) AS VALOR
		FROM
			PRODUCTS
	)
SELECT
	P.PRODUCT_NAME AS PRODUCTO,
	ROUND(P.UNIT_PRICE::NUMERIC, 2) AS PRECIO,
	ROUND(M.VALOR::NUMERIC, 2) AS PRECIO_MEDIO_CATALOGO,
	ROUND((P.UNIT_PRICE - M.VALOR)::NUMERIC, 2) AS DIFERENCIA
FROM
	PRODUCTS P
	CROSS JOIN MEDIA_CATALOGO M
WHERE
	P.DISCONTINUED = 0
	AND P.UNIT_PRICE > M.VALOR
ORDER BY
	DIFERENCIA DESC;