SELECT
	CAT.CATEGORY_NAME AS CATEGORIA,
	P.PRODUCT_NAME AS PRODUCTO,
	ROUND(P.UNIT_PRICE::NUMERIC, 2) AS PRECIO,
	ROUND(
		(
			SELECT
				AVG(P2.UNIT_PRICE)
			FROM
				PRODUCTS P2
			WHERE
				P2.CATEGORY_ID = P.CATEGORY_ID
		)::NUMERIC,
		2
	) AS PRECIO_MEDIO_CATEGORIA
FROM
	PRODUCTS P
	JOIN CATEGORIES CAT ON P.CATEGORY_ID = CAT.CATEGORY_ID
WHERE
	P.UNIT_PRICE = (
		SELECT
			MAX(P3.UNIT_PRICE)
		FROM
			PRODUCTS P3
		WHERE
			P3.CATEGORY_ID = P.CATEGORY_ID
	)
ORDER BY
	CATEGORIA;