WITH
	FACTURACION_CLIENTE AS (
		SELECT
			C.CUSTOMER_ID,
			SUM(OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT)) AS TOTAL
		FROM
			CUSTOMERS C
			JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
			JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
		GROUP BY
			C.CUSTOMER_ID
	),
	CUARTILES AS (
		SELECT
			CUSTOMER_ID,
			TOTAL,
			NTILE(4) OVER (
				ORDER BY
					TOTAL DESC
			) AS CUARTIL
		FROM
			FACTURACION_CLIENTE
	),
	SEGMENTOS AS (
		SELECT
			TOTAL,
			CASE CUARTIL
				WHEN 1 THEN 'A - Estratégico'
				WHEN 2 THEN 'B - Consolidado'
				WHEN 3 THEN 'C - Ocasional'
				WHEN 4 THEN 'D - Marginal'
			END AS SEGMENTO
		FROM
			CUARTILES
	)
SELECT
	SEGMENTO,
	COUNT(*) AS NUM_CLIENTES,
	ROUND(SUM(TOTAL)::NUMERIC, 2) AS FACTURACION_SEGMENTO,
	ROUND(
		(
			100.0 * SUM(TOTAL) / (
				SELECT
					SUM(TOTAL)
				FROM
					FACTURACION_CLIENTE
			)
		)::NUMERIC,
		2
	) AS PORCENTAJE_SOBRE_TOTAL
FROM
	SEGMENTOS
GROUP BY
	SEGMENTO
ORDER BY
	SEGMENTO;